# gcloud builds submit --config=cloudbuild.yaml .
steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: 
    - '-c'
    - |
       gcloud secrets versions access latest --secret=pulumi-credentials --format='get(payload.data)' | tr '_-' '/+' | base64 -d > credentials.json
- name: us-central1-docker.pkg.dev/streamprocessor-org/builder/pulumi-node:latest
  entrypoint: "bash"
  args:
    - '-c'
    - |
       export GOOGLE_CREDENTIALS=$$(cat credentials.json)
       export GOOGLE_APPLICATION_CREDENTIALS=credentials.json
       export PULUMI_CONFIG_PASSPHRASE=""
       pulumi login --cloud-url ${_STATE_BUCKET}
       pulumi stack init ${_STACK} --secrets-provider="gcpkms://projects/${PROJECT_ID}/locations/global/keyRings/${_GOOGLE_KEY_RING}/cryptoKeys/${_GOOGLE_CRYPTO_KEY}"
       pulumi stack select ${_STACK}
       #pulumi stack ls
       npm install
       pulumi config set gcp:project ${PROJECT_ID} --non-interactive 
       pulumi config set gcp:region ${_GOOGLE_REGION} --non-interactive 
       pulumi config set gcp:zone ${_GOOGLE_ZONE} --non-interactive 
       pulumi config set serviceAccountName ${_SERVICE_ACCOUNT_NAME} --non-interactive 
       pulumi preview --non-interactive
       pulumi stack export | pulumi stack import
       pulumi refresh --yes
       pulumi up --yes
       #pulumi stack graph tmp.gv
       #cat tmp.gv
       pulumi stack output --json
tags: ['streamprocessor-builder']
substitutions:
  _STATE_BUCKET: gs://${PROJECT_ID}-state
  _STACK: 'infra'
  _GOOGLE_REGION: 'europe-west1'
  _GOOGLE_ZONE: 'europe-west1-b'
  _GOOGLE_KEY_RING: 'streamprocessor'
  _GOOGLE_CRYPTO_KEY: 'pulumi'
  _SERVICE_ACCOUNT_NAME: streamprocessor@${PROJECT_ID}-setup.iam.gserviceaccount.com